version: "3.7"

services:
  database_desafio_chapter04:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=fin_api
    volumes:
      - pgdata:/data/postgres


volumes:
  pgdata:
    driver: local
